### ISSUE TITLE
Subitems as new state

### ISSUE THREAD

**Issue by Haasie** [leeuwte/home-assistant-p2000#2]
Hello,
Is it possible to make a new state from the subitems that some messages have? Now it is hard to filter some specific data.
Thank you

**Comment by leeuwte** [comment]
@Haasie Not exactly clear what you mean. Can you give an example?

**Comment by Haasie** [comment]
Net an exact example at the moment, have to wait for new message that contains it.

Many a better description:
When you have resuscitation, the fire department will be alarmed.
The api in use ad this to the original message as subitem. For me it is not possible to extract attributes from the extra subitem.

**Comment by leeuwte** [comment]
From this screenshot you're referring to the capcodes I think? Those are the only ones which contain sub-items;

<img width="1040" alt="Screenshot 2021-12-01 at 18 46 25" src="https://user-images.githubusercontent.com/2683564/144286285-04fa0507-fd2b-49b8-b80f-925dd26f4110.png">

**Comment by Haasie** [comment]
This is the message on the site as i mean 

https://www.alarmeringdroid.nl/toonmelding/18182820

Here you have 2 follow up massages that i cant filter (on "blusploeg a" or something like that.

**Comment by leeuwte** [comment]
Ah ok. Now I get what you mean... I actually can't figure out yet how those are connected. 🤔

**Comment by huizebruin** [comment]
![unknown-6.png](https://user-images.githubusercontent.com/62996429/144299379-b02d4024-08c9-48a6-ba6a-c6e8a2973d73.png)

Did you mean this?
Every line is a new information line from the add-on

**Comment by Haasie** [comment]
no, it is not exactly what i mend. but i will try this, looks awesome :)
