### ISSUE TITLE
Error about device_state_attributes

### ISSUE THREAD

**Issue by the-cyberspace** [leeuwte/home-assistant-p2000#5]
After upgrading to 2021.12.b2 I'm seeing this warning in my logs:

Logger: homeassistant.helpers.entity
Source: helpers/entity.py:549
First occurred: 19:07:28 (4 occurrences)
Last logged: 19:07:29

Entity sensor.p2000_doetinchem (<class 'custom_components.p2000.sensor.P2000Sensor'>) implements device_state_attributes. Please report it to the custom component author.

Read about it in the official HA discord server and found this:
"device_state_attributes -> extra_state_attributes, is a name change... its really just that"

**Comment by leeuwte** [comment]
it. has been fixed with #6
