### ISSUE TITLE
No p2000 information any more

### ISSUE THREAD

**Issue by canedje** [leeuwte/home-assistant-p2000#9]
Since yesterday I do not receive p2000 information anymore like altitude and logitude.
Is there something changed?
I do receive a message but without information

Our gemeente is changed in dijk en waard instead of langedijk an heerhugowaard, could that be the problem?

EDIT: I changed the gemeente, the same problem

**Comment by Haasie** [comment]
Same issue

**Comment by peer48** [comment]
Same issue

**Comment by ArnolddeBolster** [comment]
still works and maybe change gemeente in "dijk en waard" will help ?

**Comment by EdwinKort** [comment]
Error with gemeenten

'gemeenten' is an invalid option for 'p2000.sensor', check: gemeenten,

**Comment by ArnolddeBolster** [comment]
for me it worked
  gemeenten:
    - "'s-gravenhage"
    - delft
    - leidschendam-voorburg
    - midden-delfland
    - pijnacker-nootdorp

**Comment by EdwinKort** [comment]
Trying again,. Still new with Homeassistant, and I think there is still the other p2000 monitor hidden.

**Comment by ArnolddeBolster** [comment]
@EdKo66 I'm checking with Noord-Holland Noord

**Comment by EdwinKort** [comment]
I'm in Rotterdam-Rijnmond, regio 17

#P2000 test
# Example configuration.yaml entry
  - platform: p2000
    name: p2000
    gemeenten:
      - Rhoon

**Comment by ArnolddeBolster** [comment]
- platform: p2000
  name: p2000
  gemeenten:
     - rhoon
  
should work I will check

**Comment by EdwinKort** [comment]
In HA's logbook I can now see that p2000 has changed to 22024090... So I guess it's now time to wait for alert in my region

**Comment by ArnolddeBolster** [comment]
@EdKo66 fingers crossed

rhoon is part of albrandswaard

**Comment by EdwinKort** [comment]
Ah.. So I should have used the city instead of the village name. Let's see what happens.  Trying this weekend.

**Comment by EdwinKort** [comment]
Got it working now, It seemed there were two versions of the p2000 sensor. Deleted them both and after restarting HA everything was working

**Comment by ArnolddeBolster** [comment]
so now it's working again this issue can be closed in my opinion

**Comment by ArnolddeBolster** [comment]
@leeuwte this can be closed ?

**Comment by EdwinKort** [comment]
As far as I'm concerned, it can. But I'm not the topic starter.
